package io.renren.entity.manage;

import java.io.Serializable;
import java.util.Date;

public class ActivityJoinInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.id
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.activity_code
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private String activityCode;

    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.name
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.mobile
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.pic
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.description
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.status
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.update_time
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_join_info.create_time
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.id
     *
     * @return the value of activity_join_info.id
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.id
     *
     * @param id the value for activity_join_info.id
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.activity_code
     *
     * @return the value of activity_join_info.activity_code
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.activity_code
     *
     * @param activityCode the value for activity_join_info.activity_code
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }

    public String getActivityName() {
        return activityName;
    }

    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.name
     *
     * @return the value of activity_join_info.name
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.name
     *
     * @param name the value for activity_join_info.name
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.mobile
     *
     * @return the value of activity_join_info.mobile
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.mobile
     *
     * @param mobile the value for activity_join_info.mobile
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.pic
     *
     * @return the value of activity_join_info.pic
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.pic
     *
     * @param pic the value for activity_join_info.pic
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.description
     *
     * @return the value of activity_join_info.description
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.description
     *
     * @param description the value for activity_join_info.description
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.status
     *
     * @return the value of activity_join_info.status
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.status
     *
     * @param status the value for activity_join_info.status
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.update_time
     *
     * @return the value of activity_join_info.update_time
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.update_time
     *
     * @param updateTime the value for activity_join_info.update_time
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_join_info.create_time
     *
     * @return the value of activity_join_info.create_time
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_join_info.create_time
     *
     * @param createTime the value for activity_join_info.create_time
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", activityCode=").append(activityCode);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append(", pic=").append(pic);
        sb.append(", description=").append(description);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ActivityJoinInfo other = (ActivityJoinInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getActivityCode() == null ? other.getActivityCode() == null : this.getActivityCode().equals(other.getActivityCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getActivityCode() == null) ? 0 : getActivityCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}