package io.renren.entity.manage;

import java.io.Serializable;
import java.util.Date;

public class App implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.appid
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.name
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.courseid
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.createtime
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_app.dr
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private Integer dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.appid
     *
     * @return the value of bd_app.appid
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.appid
     *
     * @param appid the value for bd_app.appid
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.code
     *
     * @return the value of bd_app.code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.code
     *
     * @param code the value for bd_app.code
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.name
     *
     * @return the value of bd_app.name
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.name
     *
     * @param name the value for bd_app.name
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.courseid
     *
     * @return the value of bd_app.courseid
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.courseid
     *
     * @param courseid the value for bd_app.courseid
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid == null ? null : courseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.province
     *
     * @return the value of bd_app.province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.province
     *
     * @param province the value for bd_app.province
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.createtime
     *
     * @return the value of bd_app.createtime
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.createtime
     *
     * @param createtime the value for bd_app.createtime
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_app.dr
     *
     * @return the value of bd_app.dr
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_app.dr
     *
     * @param dr the value for bd_app.dr
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appid=").append(appid);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", courseid=").append(courseid);
        sb.append(", province=").append(province);
        sb.append(", createtime=").append(createtime);
        sb.append(", dr=").append(dr);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        App other = (App) that;
        return (this.getAppid() == null ? other.getAppid() == null : this.getAppid().equals(other.getAppid()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCourseid() == null ? other.getCourseid() == null : this.getCourseid().equals(other.getCourseid()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppid() == null) ? 0 : getAppid().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCourseid() == null) ? 0 : getCourseid().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        return result;
    }
}