package io.renren.entity.manage;

import java.io.Serializable;

public class NcCourse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_course.courseid
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_course.code
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_course.nccode
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private String nccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_course.name
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_course.ncname
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private String ncname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nc_course.dr
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private Integer dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nc_course
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_course.courseid
     *
     * @return the value of nc_course.courseid
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_course.courseid
     *
     * @param courseid the value for nc_course.courseid
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_course.code
     *
     * @return the value of nc_course.code
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_course.code
     *
     * @param code the value for nc_course.code
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_course.nccode
     *
     * @return the value of nc_course.nccode
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public String getNccode() {
        return nccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_course.nccode
     *
     * @param nccode the value for nc_course.nccode
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public void setNccode(String nccode) {
        this.nccode = nccode == null ? null : nccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_course.name
     *
     * @return the value of nc_course.name
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_course.name
     *
     * @param name the value for nc_course.name
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_course.ncname
     *
     * @return the value of nc_course.ncname
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public String getNcname() {
        return ncname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_course.ncname
     *
     * @param ncname the value for nc_course.ncname
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public void setNcname(String ncname) {
        this.ncname = ncname == null ? null : ncname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nc_course.dr
     *
     * @return the value of nc_course.dr
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public Integer getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nc_course.dr
     *
     * @param dr the value for nc_course.dr
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    public void setDr(Integer dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_course
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courseid=").append(courseid);
        sb.append(", code=").append(code);
        sb.append(", nccode=").append(nccode);
        sb.append(", name=").append(name);
        sb.append(", ncname=").append(ncname);
        sb.append(", dr=").append(dr);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_course
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NcCourse other = (NcCourse) that;
        return (this.getCourseid() == null ? other.getCourseid() == null : this.getCourseid().equals(other.getCourseid()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getNccode() == null ? other.getNccode() == null : this.getNccode().equals(other.getNccode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNcname() == null ? other.getNcname() == null : this.getNcname().equals(other.getNcname()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nc_course
     *
     * @mbggenerated Thu Aug 10 14:22:20 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCourseid() == null) ? 0 : getCourseid().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getNccode() == null) ? 0 : getNccode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNcname() == null) ? 0 : getNcname().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        return result;
    }
}