package io.renren.entity.manage;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.dr
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Byte dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.school_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nick_name
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.pic
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.creator
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.creation_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.modifier
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.modified_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_login_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_login_ip
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.channel
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Byte channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.remake
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String remake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nc_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private String ncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.dept_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.dr
     *
     * @return the value of users.dr
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Byte getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.dr
     *
     * @param dr the value for users.dr
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setDr(Byte dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.school_id
     *
     * @return the value of users.school_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.school_id
     *
     * @param schoolId the value for users.school_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile
     *
     * @return the value of users.mobile
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile
     *
     * @param mobile the value for users.mobile
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nick_name
     *
     * @return the value of users.nick_name
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nick_name
     *
     * @param nickName the value for users.nick_name
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pic
     *
     * @return the value of users.pic
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pic
     *
     * @param pic the value for users.pic
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.creator
     *
     * @return the value of users.creator
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.creator
     *
     * @param creator the value for users.creator
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.creation_time
     *
     * @return the value of users.creation_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.creation_time
     *
     * @param creationTime the value for users.creation_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.modifier
     *
     * @return the value of users.modifier
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.modifier
     *
     * @param modifier the value for users.modifier
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.modified_time
     *
     * @return the value of users.modified_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.modified_time
     *
     * @param modifiedTime the value for users.modified_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_login_time
     *
     * @return the value of users.last_login_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_login_time
     *
     * @param lastLoginTime the value for users.last_login_time
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_login_ip
     *
     * @return the value of users.last_login_ip
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_login_ip
     *
     * @param lastLoginIp the value for users.last_login_ip
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.channel
     *
     * @return the value of users.channel
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.channel
     *
     * @param channel the value for users.channel
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.remake
     *
     * @return the value of users.remake
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getRemake() {
        return remake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.remake
     *
     * @param remake the value for users.remake
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nc_id
     *
     * @return the value of users.nc_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public String getNcId() {
        return ncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nc_id
     *
     * @param ncId the value for users.nc_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setNcId(String ncId) {
        this.ncId = ncId == null ? null : ncId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.dept_id
     *
     * @return the value of users.dept_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.dept_id
     *
     * @param deptId the value for users.dept_id
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", dr=").append(dr);
        sb.append(", schoolId=").append(schoolId);
        sb.append(", mobile=").append(mobile);
        sb.append(", nickName=").append(nickName);
        sb.append(", pic=").append(pic);
        sb.append(", status=").append(status);
        sb.append(", sex=").append(sex);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", creator=").append(creator);
        sb.append(", creationTime=").append(creationTime);
        sb.append(", modifier=").append(modifier);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", channel=").append(channel);
        sb.append(", remake=").append(remake);
        sb.append(", ncId=").append(ncId);
        sb.append(", deptId=").append(deptId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Users other = (Users) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getSchoolId() == null ? other.getSchoolId() == null : this.getSchoolId().equals(other.getSchoolId()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreationTime() == null ? other.getCreationTime() == null : this.getCreationTime().equals(other.getCreationTime()))
            && (this.getModifier() == null ? other.getModifier() == null : this.getModifier().equals(other.getModifier()))
            && (this.getModifiedTime() == null ? other.getModifiedTime() == null : this.getModifiedTime().equals(other.getModifiedTime()))
            && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null : this.getLastLoginTime().equals(other.getLastLoginTime()))
            && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null : this.getLastLoginIp().equals(other.getLastLoginIp()))
            && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
            && (this.getRemake() == null ? other.getRemake() == null : this.getRemake().equals(other.getRemake()))
            && (this.getNcId() == null ? other.getNcId() == null : this.getNcId().equals(other.getNcId()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Fri Aug 25 16:21:39 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getSchoolId() == null) ? 0 : getSchoolId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreationTime() == null) ? 0 : getCreationTime().hashCode());
        result = prime * result + ((getModifier() == null) ? 0 : getModifier().hashCode());
        result = prime * result + ((getModifiedTime() == null) ? 0 : getModifiedTime().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        result = prime * result + ((getRemake() == null) ? 0 : getRemake().hashCode());
        result = prime * result + ((getNcId() == null) ? 0 : getNcId().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        return result;
    }
}