package io.renren.dao.manage;

import io.renren.entity.manage.ActivityJoinInfo;
import io.renren.entity.manage.ActivityJoinInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.Date;
import java.util.List;

public interface ActivityJoinInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int countByExample(ActivityJoinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int deleteByExample(ActivityJoinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int insert(ActivityJoinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int insertSelective(ActivityJoinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    List<ActivityJoinInfo> selectByExampleWithRowbounds(ActivityJoinInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    List<ActivityJoinInfo> selectByExample(ActivityJoinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    ActivityJoinInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") ActivityJoinInfo record, @Param("example") ActivityJoinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int updateByExample(@Param("record") ActivityJoinInfo record, @Param("example") ActivityJoinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityJoinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_join_info
     *
     * @mbggenerated Thu Dec 07 11:29:05 CST 2017
     */
    int updateByPrimaryKey(ActivityJoinInfo record);

    int updateStatusById(@Param("ids") int[] ids, @Param("status") Integer status, @Param("updateTime") Date updateTime);
}