package io.renren.dao.manage;

import io.renren.entity.manage.AppAccount;
import io.renren.entity.manage.AppAccountExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.Date;
import java.util.List;

public interface AppAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int countByExample(AppAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int deleteByExample(AppAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int deleteByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int insert(AppAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int insertSelective(AppAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    List<AppAccount> selectByExampleWithRowbounds(AppAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    List<AppAccount> selectByExample(AppAccountExample example);

    AppAccount selectByExampleFetchOne(AppAccountExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    AppAccount selectByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppAccount record, @Param("example") AppAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int updateByExample(@Param("record") AppAccount record, @Param("example") AppAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int updateByPrimaryKeySelective(AppAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app_account
     *
     * @mbggenerated Thu Sep 28 09:56:30 CST 2017
     */
    int updateByPrimaryKey(AppAccount record);

    int updateDrByPrimaryKey(@Param("dr") Integer dr, @Param("accountid") Integer accountid);

    int updatePTByUsernameAppid(@Param("userpass") String userpass, @Param("createtime") Date createtime,
                                @Param("username") String username, @Param("appid") Integer appid);
}