package io.renren.dao.manage;

import io.renren.entity.manage.App;
import io.renren.entity.manage.AppExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int countByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int deleteByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int deleteByPrimaryKey(Integer appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int insertSelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    List<App> selectByExampleWithRowbounds(AppExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    List<App> selectByExample(AppExample example);

    App selectByExampleFetchOne(AppExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    App selectByPrimaryKey(Integer appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") App record, @Param("example") AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByExample(@Param("record") App record, @Param("example") AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByPrimaryKeySelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_app
     *
     * @mbggenerated Mon Aug 14 09:39:43 CST 2017
     */
    int updateByPrimaryKey(App record);
}