
package io.renren.ws.chapterinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService1Soap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetClassJobStatisticsInfoInfo", action = "http://tempuri.org/GetClassJobStatisticsInfoInfo")
    @WebResult(name = "GetClassJobStatisticsInfoInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClassJobStatisticsInfoInfo", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassJobStatisticsInfoInfo")
    @ResponseWrapper(localName = "GetClassJobStatisticsInfoInfoResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassJobStatisticsInfoInfoResponse")
    public String getClassJobStatisticsInfoInfo();

    /**
     * 
     * @param classNCCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetClassCompletionrateByClassCode", action = "http://tempuri.org/GetClassCompletionrateByClassCode")
    @WebResult(name = "GetClassCompletionrateByClassCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClassCompletionrateByClassCode", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassCompletionrateByClassCode")
    @ResponseWrapper(localName = "GetClassCompletionrateByClassCodeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassCompletionrateByClassCodeResponse")
    public String getClassCompletionrateByClassCode(
        @WebParam(name = "ClassNCCode", targetNamespace = "http://tempuri.org/")
        String classNCCode);

    /**
     * 
     * @param date
     * @param classNCCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetClassCompletionrateByClassCodeAndDate", action = "http://tempuri.org/GetClassCompletionrateByClassCodeAndDate")
    @WebResult(name = "GetClassCompletionrateByClassCodeAndDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClassCompletionrateByClassCodeAndDate", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassCompletionrateByClassCodeAndDate")
    @ResponseWrapper(localName = "GetClassCompletionrateByClassCodeAndDateResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassCompletionrateByClassCodeAndDateResponse")
    public String getClassCompletionrateByClassCodeAndDate(
        @WebParam(name = "ClassNCCode", targetNamespace = "http://tempuri.org/")
        String classNCCode,
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        String date);

    /**
     * 
     * @param date
     * @param areaCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetClassCompletionrateByDateAndAreaCode", action = "http://tempuri.org/GetClassCompletionrateByDateAndAreaCode")
    @WebResult(name = "GetClassCompletionrateByDateAndAreaCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClassCompletionrateByDateAndAreaCode", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassCompletionrateByDateAndAreaCode")
    @ResponseWrapper(localName = "GetClassCompletionrateByDateAndAreaCodeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassCompletionrateByDateAndAreaCodeResponse")
    public String getClassCompletionrateByDateAndAreaCode(
        @WebParam(name = "Date", targetNamespace = "http://tempuri.org/")
        String date,
        @WebParam(name = "AreaCode", targetNamespace = "http://tempuri.org/")
        String areaCode);

    /**
     * 
     * @param getStudentCompletionrateByUpdateTimeResult
     * @param pageCount
     * @param isOK
     * @param startTime
     * @param pageNum
     */
    @WebMethod(operationName = "GetStudentCompletionrateByUpdateTime", action = "http://tempuri.org/GetStudentCompletionrateByUpdateTime")
    @RequestWrapper(localName = "GetStudentCompletionrateByUpdateTime", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentCompletionrateByUpdateTime")
    @ResponseWrapper(localName = "GetStudentCompletionrateByUpdateTimeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentCompletionrateByUpdateTimeResponse")
    public void getStudentCompletionrateByUpdateTime(
        @WebParam(name = "StartTime", targetNamespace = "http://tempuri.org/")
        String startTime,
        @WebParam(name = "PageCount", targetNamespace = "http://tempuri.org/")
        int pageCount,
        @WebParam(name = "PageNum", targetNamespace = "http://tempuri.org/")
        int pageNum,
        @WebParam(name = "GetStudentCompletionrateByUpdateTimeResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> getStudentCompletionrateByUpdateTimeResult,
        @WebParam(name = "isOK", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> isOK);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetClassJobStatisticsInfo_Sync_To_NCByTime", action = "http://tempuri.org/GetClassJobStatisticsInfo_Sync_To_NCByTime")
    @WebResult(name = "GetClassJobStatisticsInfo_Sync_To_NCByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClassJobStatisticsInfo_Sync_To_NCByTime", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassJobStatisticsInfoSyncToNCByTime")
    @ResponseWrapper(localName = "GetClassJobStatisticsInfo_Sync_To_NCByTimeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetClassJobStatisticsInfoSyncToNCByTimeResponse")
    public String getClassJobStatisticsInfoSyncToNCByTime(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetKJSCExamDetailInfo_SyncToNCByTime", action = "http://tempuri.org/GetKJSCExamDetailInfo_SyncToNCByTime")
    @WebResult(name = "GetKJSCExamDetailInfo_SyncToNCByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetKJSCExamDetailInfo_SyncToNCByTime", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetKJSCExamDetailInfoSyncToNCByTime")
    @ResponseWrapper(localName = "GetKJSCExamDetailInfo_SyncToNCByTimeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetKJSCExamDetailInfoSyncToNCByTimeResponse")
    public String getKJSCExamDetailInfoSyncToNCByTime(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetETSBusinessOpportunityInfo_SyncToNCByTime", action = "http://tempuri.org/GetETSBusinessOpportunityInfo_SyncToNCByTime")
    @WebResult(name = "GetETSBusinessOpportunityInfo_SyncToNCByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetETSBusinessOpportunityInfo_SyncToNCByTime", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetETSBusinessOpportunityInfoSyncToNCByTime")
    @ResponseWrapper(localName = "GetETSBusinessOpportunityInfo_SyncToNCByTimeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetETSBusinessOpportunityInfoSyncToNCByTimeResponse")
    public String getETSBusinessOpportunityInfoSyncToNCByTime(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStudentOfClassEndingTaskComplianceRateByTime", action = "http://tempuri.org/GetStudentOfClassEndingTaskComplianceRateByTime")
    @WebResult(name = "GetStudentOfClassEndingTaskComplianceRateByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStudentOfClassEndingTaskComplianceRateByTime", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingTaskComplianceRateByTime")
    @ResponseWrapper(localName = "GetStudentOfClassEndingTaskComplianceRateByTimeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingTaskComplianceRateByTimeResponse")
    public String getStudentOfClassEndingTaskComplianceRateByTime(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStudentOfClassEndingExamComplianceRateByTime", action = "http://tempuri.org/GetStudentOfClassEndingExamComplianceRateByTime")
    @WebResult(name = "GetStudentOfClassEndingExamComplianceRateByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStudentOfClassEndingExamComplianceRateByTime", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingExamComplianceRateByTime")
    @ResponseWrapper(localName = "GetStudentOfClassEndingExamComplianceRateByTimeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingExamComplianceRateByTimeResponse")
    public String getStudentOfClassEndingExamComplianceRateByTime(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param studentNCCode
     * @param courseCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCode", action = "http://tempuri.org/GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCode")
    @WebResult(name = "GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCode", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCode")
    @ResponseWrapper(localName = "GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCodeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCodeResponse")
    public String getStudentOfClassEndingExamComplianceRateByStudentNCCodeAndCourseCode(
        @WebParam(name = "StudentNCCode", targetNamespace = "http://tempuri.org/")
        String studentNCCode,
        @WebParam(name = "CourseCode", targetNamespace = "http://tempuri.org/")
        String courseCode);

    /**
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetStudentOfClassEndingExamComplianceRateByTime_BI", action = "http://tempuri.org/GetStudentOfClassEndingExamComplianceRateByTime_BI")
    @WebResult(name = "GetStudentOfClassEndingExamComplianceRateByTime_BIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStudentOfClassEndingExamComplianceRateByTime_BI", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingExamComplianceRateByTimeBI")
    @ResponseWrapper(localName = "GetStudentOfClassEndingExamComplianceRateByTime_BIResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetStudentOfClassEndingExamComplianceRateByTimeBIResponse")
    public String getStudentOfClassEndingExamComplianceRateByTimeBI(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetChapterInfo_HQZX", action = "http://tempuri.org/GetChapterInfo_HQZX")
    @WebResult(name = "GetChapterInfo_HQZXResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetChapterInfo_HQZX", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetChapterInfoHQZX")
    @ResponseWrapper(localName = "GetChapterInfo_HQZXResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetChapterInfoHQZXResponse")
    public String getChapterInfoHQZX();

    /**
     * 
     * @param size
     * @param ssoKey
     * @param name
     * @param page
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getUsers")
    @WebResult(name = "getUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.GetUsersResponse")
    public String getUsers(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "size", targetNamespace = "http://tempuri.org/")
        int size,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "ssoKey", targetNamespace = "http://tempuri.org/")
        String ssoKey);

    /**
     * 
     * @param ssoKey
     * @param srcPk
     * @param guid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/upLoadSSOKey")
    @WebResult(name = "upLoadSSOKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "upLoadSSOKey", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.UpLoadSSOKey")
    @ResponseWrapper(localName = "upLoadSSOKeyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.ws.chapterinfo.UpLoadSSOKeyResponse")
    public String upLoadSSOKey(
        @WebParam(name = "src_pk", targetNamespace = "http://tempuri.org/")
        String srcPk,
        @WebParam(name = "guid", targetNamespace = "http://tempuri.org/")
        String guid,
        @WebParam(name = "ssoKey", targetNamespace = "http://tempuri.org/")
        String ssoKey);

}
